<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USZYBGH1MU" failures="0" tests="2" name="demo.tests.scp.loginTests" time="227.150" errors="1" timestamp="2023-11-09T12:01:35 IST" skipped="0">
  <testcase classname="demo.tests.scp.loginTests" name="linkandunlinkaccount" time="175.191">
    <error type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
at sew.ai.helpers.listeners.RetryFailedTest.retry(RetryFailedTest.java:15)
at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:554)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:726)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "sew.ai.utils.PropertiesUtil.applicationProps" is null
at sew.ai.utils.PropertiesUtil.getApplicationPropValue(PropertiesUtil.java:56)
at sew.ai.helpers.props.ApplicationProps.<clinit>(ApplicationProps.java:6)
... 25 more
]]>
    </error>
  </testcase> <!-- linkandunlinkaccount -->
  <testcase classname="demo.tests.scp.loginTests" name="MyAlectra" time="51.959"/>
</testsuite> <!-- demo.tests.scp.loginTests -->
